apiVersion: v1
kind: Service
metadata:
  name: statista-api
  namespace: statista
  labels:
    app: statista-api
    environment: local
spec:
  selector:
    app: statista-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: LoadBalancer  # For local access (Docker Desktop) or NodePort for Minikube 