apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: statista-api-hpa
  namespace: statista
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: statista-api
  minReplicas: 1
  maxReplicas: 5
  # Simple configuration that works without metrics server
  # Will scale based on resource requests/limits if metrics server is available
  # Otherwise, will just maintain the current replica count
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60 